### ISSUE TITLE
Add precommit

### ISSUE THREAD

**Issue by danellecline** [mbari-org/pbp#37]
To help with errors before check-in, I suggest adding a pre-commit.  

```[tasklist]
### Tasks
- [ ] Add pip install pre-commit as a dev dependency
- [ ] Create a .pre-commit-config.yaml file
- [ ] Install it `pre-commit install`
- [ ] Add  just recipes to setup the pre-commit
- [ ] Test it
```
